### ISSUE TITLE
APP_ACCESS_TOKEN is undefined|undefined

### ISSUE THREAD

**Issue by uudens** [feego/hoodie-plugin-facebook-login#1] opened 2015-09-20 13:46 UTC
Hello, nice plugin, thanks for writing it!  
It looks like there is some problem with versions between this github page and [npm packge page](https://www.npmjs.com/package/hoodie-plugin-facebook-login).
When I type `hoodie install facebook-login` following the instructions on the [npm packge page](https://www.npmjs.com/package/hoodie-plugin-facebook-login) then I get `index.js` file _before_ commit d718bcf, and thus I get an error when trying to verify facebook token because `APP_ACCESS_TOKEN` is `undefined|undefined`.  
Also I don't see github link on the [npm packge page](https://www.npmjs.com/package/hoodie-plugin-facebook-login). I usually see it for other packages.  
I don't know how to make hoodie install the plugin directly from this github page, so I temporarily fixed it by manually applying d718bcf to `index.js`

**Comment by feego** [comment] 2015-12-17 12:31
Hi, I've been away for quite a while, so I must apologize for taking so long to get back to you with an answer for this.

Anyway, thanks for reporting this. I published now the correct version of the plugin on npm, I believe the problem is now fixed!

**Closed as completed** 2015-12-17 12:46 UTC
